# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce78929ed37d5407efccf03fccfd065f9ccf898dc95efe5a59337b1830d4147ce474d40e5a07f6ec5584c204b05d8fb363635eed082b00f67f98c0a1f18ea421

test:
  secret_key_base: ae1720d3015b48a71f713e8819021d638fd4ac169902e7e6e09650df2f342b025fbffd098ef6a777483df30e5125a3dd9d9c3e051158813c3db66cc8e317142a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
